// SPDX-License-Identifier: MIT
pragma solidity ^0.8.22;

import "forge-std/Script.sol";
import "forge-std/console.sol";

import "../../src/mocks/TESTToken.sol";
import "../../src/StakingOperators.sol";
import "../../src/RewardPolicy.sol";
import "../../src/NodeOperatorFactory.sol";
import {BlacklightNodeOpsLib} from "./utils/BlacklightNodeOpsLib.sol";

/// @title DeployNodeManagers
/// @notice Deploys NodeOperatorFactory + managed node operators and writes addresses to nodemanager_addresses.env.
/// @dev Required env vars:
///      - PRIVATE_KEY
///      - STAKING_OPERATORS
///      - REWARD_POLICY
///      - STAKE_TOKEN
///      - MNEMONIC
///      - NUM_OPERATORS
///
///      Optional env vars:
///      - NUM_MANAGED_NODES (default: 0)
///      - MANAGED_NODES_OFFSET (default: NUM_OPERATORS)
///      - FACTORY_WITHDRAW_FEE_BPS (default: 3000)
///      - FACTORY_RESTAKE_FEE_BPS (default: 1500)
///      - FACTORY_MIN_STAKE (default: 1_000e6 = 1000 NIL tokens)
///      - FUNDED_NODES (default: 0)
///      - FUNDED_TOKEN_AMOUNT (required if FUNDED_NODES > 0)
///      - FUNDED_ETH_AMOUNT (required if FUNDED_NODES > 0)
contract DeployNodeManagers is Script {
    struct Output {
        NodeOperatorFactory nodeFactory;
        address[] unmanagedNodes;
        address[] managedNodes;
        address[] nodeManagers;
    }

    function run() external returns (Output memory out) {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerPrivateKey);
        bool deployNodeFactory = vm.envOr("DEPLOY_NODE_FACTORY", true);

        address stakeTokenAddr = vm.envAddress("STAKE_TOKEN");
        address stakingOpsAddr = vm.envOr("STAKING_OPERATORS", address(0));
        address rewardPolicyAddr = vm.envOr("REWARD_POLICY", address(0));
        if (deployNodeFactory) {
            require(stakingOpsAddr != address(0), "STAKING_OPERATORS required when DEPLOY_NODE_FACTORY=true");
            require(rewardPolicyAddr != address(0), "REWARD_POLICY required when DEPLOY_NODE_FACTORY=true");
        }

        vm.startBroadcast(deployerPrivateKey);

        uint256[] memory managedNodeKeys;
        (out.nodeFactory, out.managedNodes, managedNodeKeys) = BlacklightNodeOpsLib.deployNodeFactoryAndManagedNodes(
            vm, deployNodeFactory,
            deployer,
            StakingOperators(stakingOpsAddr),
            RewardPolicy(rewardPolicyAddr),
            TESTToken(stakeTokenAddr)
        );

        BlacklightNodeOpsLib.fundExtraNodes(vm, deployNodeFactory, TESTToken(stakeTokenAddr));

        vm.stopBroadcast();

        if (deployNodeFactory) {
            BlacklightNodeOpsLib.approveManagedNodeStakers(
                vm, out.managedNodes, managedNodeKeys, out.nodeFactory, StakingOperators(stakingOpsAddr)
            );
        }

        out.unmanagedNodes = _deriveUnmanagedNodes();
        out.nodeManagers = new address[](out.managedNodes.length);
        for (uint256 i = 0; i < out.managedNodes.length; i++) {
            out.nodeManagers[i] = out.nodeFactory.nodeToOperator(out.managedNodes[i]);
        }

        bool writeOutput = vm.envOr("WRITE_OUTPUT", true);
        if (writeOutput) {
            _writeNodeManagerAddresses(out);
        }

        if (deployNodeFactory) {
            console.log("NODE_OPERATOR_FACTORY:", address(out.nodeFactory));
        }
        console.log("Managed nodes:", out.managedNodes.length);
        console.log("Node managers:", out.nodeManagers.length);
        if (!writeOutput) {
            console.log("Dry-run mode: skipped writing nodemanager_addresses.env");
        }

        return out;
    }

    function _deriveUnmanagedNodes() internal view returns (address[] memory unmanagedNodes) {
        uint256 numOperators = vm.envUint("NUM_OPERATORS");
        string memory mnemonic = vm.envString("MNEMONIC");

        unmanagedNodes = new address[](numOperators);
        for (uint256 i = 0; i < numOperators; i++) {
            unmanagedNodes[i] = vm.addr(vm.deriveKey(mnemonic, uint32(i)));
        }
    }

    function _writeNodeManagerAddresses(Output memory out) internal {
        string memory output = "# NodeManager Contract Addresses\n";
        output = string.concat(output, "# Generated by DeployNodeManagers.s.sol\n\n");

        if (address(out.nodeFactory) != address(0)) {
            output = string.concat(output, "NODE_OPERATOR_FACTORY=", vm.toString(address(out.nodeFactory)), "\n");
        }

        if (out.unmanagedNodes.length != 0) {
            output = string.concat(output, "UNMANAGED_NODES=", _joinAddresses(out.unmanagedNodes), "\n");
            for (uint256 i = 0; i < out.unmanagedNodes.length; i++) {
                output = string.concat(
                    output, "UNMANAGED_NODE_", vm.toString(i), "=", vm.toString(out.unmanagedNodes[i]), "\n"
                );
            }
        }

        if (out.managedNodes.length != 0) {
            output = string.concat(output, "MANAGED_NODES=", _joinAddresses(out.managedNodes), "\n");
            for (uint256 i = 0; i < out.managedNodes.length; i++) {
                output = string.concat(
                    output, "MANAGED_NODE_", vm.toString(i), "=", vm.toString(out.managedNodes[i]), "\n"
                );
            }
        }

        if (out.nodeManagers.length != 0) {
            output = string.concat(output, "NODE_MANAGERS=", _joinAddresses(out.nodeManagers), "\n");
            for (uint256 i = 0; i < out.nodeManagers.length; i++) {
                output = string.concat(
                    output, "NODE_MANAGER_", vm.toString(i), "=", vm.toString(out.nodeManagers[i]), "\n"
                );
            }
        }

        vm.writeFile("nodemanager_addresses.env", output);
    }

    function _joinAddresses(address[] memory addrs) internal view returns (string memory out) {
        if (addrs.length == 0) return "";
        out = vm.toString(addrs[0]);
        for (uint256 i = 1; i < addrs.length; i++) {
            out = string.concat(out, ",", vm.toString(addrs[i]));
        }
    }
}
