// SPDX-License-Identifier: MIT
pragma solidity ^0.8.22;

import "forge-std/Vm.sol";
import {BlacklightTypes} from "./BlacklightTypes.sol";

library BlacklightOutputLib {
    function writeContractAddresses(Vm vm, BlacklightTypes.DeployedContracts memory deployed, bool emissionsDeployed)
        internal
    {
        string memory output = "# Blacklight Contract Addresses\n";
        output = string.concat(output, "# Generated by DeployBlacklight.s.sol\n\n");

        output = string.concat(output, "STAKE_TOKEN=", vm.toString(address(deployed.token)), "\n");
        output = string.concat(output, "STAKING_OPERATORS=", vm.toString(address(deployed.stakingOps)), "\n");
        output = string.concat(output, "WEIGHTED_COMMITTEE_SELECTOR=", vm.toString(address(deployed.selector)), "\n");
        output = string.concat(output, "PROTOCOL_CONFIG=", vm.toString(address(deployed.config)), "\n");
        output = string.concat(output, "HEARTBEAT_MANAGER=", vm.toString(address(deployed.manager)), "\n");
        output = string.concat(output, "REWARD_POLICY=", vm.toString(address(deployed.rewardPolicy)), "\n");
        output = string.concat(output, "SLASHING_POLICY=", vm.toString(deployed.slashingPolicy), "\n");

        if (emissionsDeployed) {
            output = string.concat(
                output, "EMISSIONS_CONTROLLER=", vm.toString(address(deployed.emissionsController)), "\n"
            );
            output = string.concat(output, "MOCK_L1_STANDARD_BRIDGE=", vm.toString(address(deployed.mockBridge)), "\n");
        }

        vm.writeFile("contract_addresses.env", output);
    }
}
